import "server-only";
import Client, { type BaseURL } from "@/lib/backend-client";
import { BACKEND_URL, getAuthHeaders, getWebAppOrigin } from "./http";

/**
 * Typed HTTP wrapper for the API gateway.
 *
 * This module was generated by `encore gen client` while the Go backend was
 * still alive. That backend has been retired, so the client can no longer be
 * regenerated and is now hand-maintained: edit it as an ordinary HTTP layer.
 * The gateway's routes are not the Encore API surface, so the generated method
 * names below should be read as convenience wrappers rather than a contract
 * that a generator will reproduce.
 *
 * Auth lives at `/_aigiare/auth/*` and identity at `/_aigiare/api/me`, both
 * served by the gateway through the same prefix the browser uses.
 */

/**
 * A fetch that carries the caller's credentials and this site's origin.
 *
 * The generated client only knows about the `Authorization` header, because Encore
 * deliberately leaves cookies out of client auth payloads. Supplying a `fetcher`
 * is the supported way to add them.
 */
async function backendFetch(input: RequestInfo | URL, init?: RequestInit): Promise<Response> {
  const headers = new Headers(init?.headers);

  for (const [name, value] of Object.entries(await getAuthHeaders())) {
    headers.set(name, value);
  }

  const origin = await getWebAppOrigin();
  if (origin) headers.set("origin", origin);

  // Encore's own API is always JSON, including on writes without a body.
  if (init?.method && init.method !== "GET" && init.method !== "HEAD") {
    if (!headers.has("content-type")) headers.set("content-type", "application/json");
  }

  return fetch(input, { ...init, headers, cache: "no-store" });
}

let client: Client | undefined;

/** Returns the shared backend client. Safe to call outside a request scope. */
export function backend(): Client {
  // Cached because the per-request state lives in backendFetch, not in the client.
  client ??= new Client(BACKEND_URL as BaseURL, { fetcher: backendFetch });
  return client;
}
